# -*- coding: utf-8 -*-
"""狼友小作文整理

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdV6p5GSJOomj-M0nczAaMaOlg1JK9gR
"""

#@title 專案初始化：掛載 Drive 並建立資料夾

import os
from google.colab import drive

# 1. 掛載 Google Drive
drive.mount("/content/drive", force_remount=True)

# 2. 設定專案根目錄名稱（你可以改成自己想要的字串）
PROJECT_ROOT_NAME = "wolf_small_report"  #@param {type:"string"}

# 3. 在 MyDrive 底下建立專案資料夾樹
MYDRIVE = "/content/drive/MyDrive"
PROJECT_ROOT = os.path.join(MYDRIVE, PROJECT_ROOT_NAME)

DIRS = {
    "root": PROJECT_ROOT,
    "raw": os.path.join(PROJECT_ROOT, "raw"),
    "docs": os.path.join(PROJECT_ROOT, "docs"),
    "output": os.path.join(PROJECT_ROOT, "output"),
    "output_md": os.path.join(PROJECT_ROOT, "output", "md"),
    "output_db": os.path.join(PROJECT_ROOT, "output", "db"),
    "output_reports": os.path.join(PROJECT_ROOT, "output", "reports"),
}

for name, path in DIRS.items():
    os.makedirs(path, exist_ok=True)

print("=== 專案資料夾初始化完成 ===")
for name, path in DIRS.items():
    print(f"{name:12s} -> {path}")

#@title 解析 LINE TXT，產生連結清單 links.csv

import os
import re
import csv
from datetime import datetime

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
RAW_DIR = os.path.join(PROJECT_ROOT, "raw")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")
RAW_FILENAME = "-LINE- 小作文天地的聊天記錄20251205_1652.txt"  #@param {type:"string"}

raw_path = os.path.join(RAW_DIR, RAW_FILENAME)
links_csv_path = os.path.join(OUTPUT_DIR, "links.csv")

url_pattern = re.compile(r"https?://\S+") # Corrected: Removed extra backslash

records = []
current_date = None
pending_line = None  # 暫存「文字在上一行、網址在下一行」的情況

with open(raw_path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n") # Corrected: Stripping standard newline character

        # 1. 判斷是否為日期行，例如：2025/5/2（週五）
        if re.match(r"^\d{4}/\d{1,2}/\d{1,2}", line): # Corrected: Date regex pattern
            current_date = line.strip()
            pending_line = None
            continue

        if not line.strip():
            continue

        parts = line.split("\t")
        if len(parts) < 3:
            # 可能是只有網址的一行，或其他系統訊息
            # 嘗試從這一行抓網址，若有且有 pending_line，就跟上一行合併
            urls = url_pattern.findall(line)
            if urls and pending_line is not None:
                url = urls[0]
                # Extract author_id from pending_line's author, excluding emojis
                filtered_author_from_pending = re.sub(r'[^一-龥0-9a-zA-Z]', '', pending_line.get("author") or "")
                author_id_from_pending = filtered_author_from_pending[:3]
                rec = {
                    "id": len(records) + 1,
                    "date": pending_line.get("date"),
                    "time": pending_line.get("time"),
                    "author_id": author_id_from_pending,
                    "author": pending_line.get("author"),
                    "text": pending_line.get("text"),
                    "link": url,
                }
                records.append(rec)
                pending_line = None
            continue

        time_str, author_raw, content = parts[0].strip(), parts[1].strip(), parts[2].strip()
        datetime_str = f"{current_date} {time_str}" if current_date else ""
        urls = url_pattern.findall(content)

        # Extract the first three digits for author_id, excluding emojis
        filtered_author_raw = re.sub(r'[^一-龥0-9a-zA-Z]', '', author_raw)
        author_id = filtered_author_raw[:3]

        if urls:
            # 同一行就有網址
            url = urls[0]
            text_without_url = url_pattern.sub("", content).strip()
            rec = {
                "id": len(records) + 1,
                "date": datetime_str,
                "time": time_str,
                "author_id": author_id,
                "author": author_raw,
                "text": text_without_url,
                "link": url,
            }
            records.append(rec)
            pending_line = None
        else:
            # 沒有網址，先暫存，有可能下一行才是純網址
            pending_line = {
                "date": datetime_str,
                "time": time_str,
                "author": author_raw,
                "text": content,
            }

# 將結果寫入 CSV，id 就是你要的 name（編號）
fieldnames = ["id", "date", "time", "author_id", "author", "text", "link"]
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(links_csv_path, "w", encoding="utf-8", newline="") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for rec in records:
        writer.writerow(rec)

print(f"共解析出 {len(records)} 筆連結，已寫入：{links_csv_path}")

print("\n前 10 筆預覽：")
for rec in records[:10]:
    print(
        f"{rec['id']:3d} | {rec['date']} | {rec['author_id']} | {rec['author']} | "
        f"text={rec['text'][:30]} | link={rec['link']}"
    )

#@title 統計 author / id 出現次數

import os
import pandas as pd

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_csv_path = os.path.join(PROJECT_ROOT, "output", "links.csv")

df = pd.read_csv(links_csv_path)

# 統計 author 欄位的種類與次數
author_counts = df["author"].value_counts(dropna=False)

print(f"總共有 {author_counts.shape[0]} 種不同的 author / id\n")

print("出現次數前 20 名：")
for author, cnt in author_counts.head(20).items():
    print(f"{author:30s} -> {cnt:4d}")

# 若你還有單獨的「數字 id」欄位（例如叫 code），可以再多做一個統計：
if "code" in df.columns:
    code_counts = df["code"].value_counts(dropna=False)
    print(f"\n總共有 {code_counts.shape[0]} 種不同的 code\n")
    print("code 出現次數前 20 名：")
    for code, cnt in code_counts.head(20).items():
        print(f"{str(code):6s} -> {cnt:4d}")

#@title bk統計 author / id 出現次數

import os
import pandas as pd

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_csv_path = os.path.join(PROJECT_ROOT, "output", "links.csv")

df = pd.read_csv(links_csv_path)

# 統計 author 欄位的種類與次數
author_counts = df["author"].value_counts(dropna=False)

print(f"總共有 {author_counts.shape[0]} 種不同的 author / id\n")

print("出現次數前 20 名：")
for author, cnt in author_counts.head(20).items():
    print(f"{author:30s} -> {cnt:4d}")

# 若你還有單獨的「數字 id」欄位（例如叫 code），可以再多做一個統計：
if "code" in df.columns:
    code_counts = df["code"].value_counts(dropna=False)
    print(f"\n總共有 {code_counts.shape[0]} 種不同的 code\n")
    print("code 出現次數前 20 名：")
    for code, cnt in code_counts.head(20).items():
        print(f"{str(code):6s} -> {cnt:4d}")

"""# Task
Analyze the types of links in the `df` DataFrame by extracting domain names, counting their frequencies, displaying the top domains, and visualizing their distribution.

## Extract Domains from Links

### Subtask:
Extract the domain name from each URL in the 'link' column of the DataFrame `df`. A new column, 'domain', will be created to store these extracted domains.

**Reasoning**:
First, I'll import the necessary `urlparse` function from `urllib.parse` to handle URL parsing. This is the first step in extracting domain names as per the instructions.
"""

from urllib.parse import urlparse

print("Imported urlparse from urllib.parse.")

"""**Reasoning**:
Now that `urlparse` is imported, I will define a function to extract the domain from a URL, apply it to the 'link' column to create a new 'domain' column in the DataFrame, and then display the first few rows to verify the changes, as per the instructions.


"""

def extract_domain(url):
    try:
        parsed_url = urlparse(url)
        return parsed_url.netloc
    except Exception as e:
        return None

df['domain'] = df['link'].apply(extract_domain)

print("First 5 rows of the DataFrame with the new 'domain' column:")
print(df[['link', 'domain']].head())



#@title 為每筆連結加上 domain / source_type 欄位

import os
import pandas as pd
from urllib.parse import urlparse

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_csv_path = os.path.join(PROJECT_ROOT, "output", "links.csv")
links_typed_csv_path = os.path.join(PROJECT_ROOT, "output", "links_with_type.csv")

df = pd.read_csv(links_csv_path)

def extract_domain(url: str) -> str:
    try:
        netloc = urlparse(url).netloc
        return netloc.lower()
    except Exception:
        return ""

def classify_source(domain: str) -> str:
    if "docs.google.com" in domain:
        return "gdocs"
    if "drive.google.com" in domain:
        return "gdrive_file"
    if domain in {"reurl.cc", "tinyurl.com", "bit.ly"}:
        return "short_url"
    if domain.endswith(".notion.site") or "notion.so" in domain:
        return "notion"
    if "dropbox.com" in domain:
        return "dropbox"
    if "hackmd.io" in domain:
        return "hackmd"
    if "youtu.be" in domain or "youtube.com" in domain:
        return "youtube"
    if "facebook.com" in domain:
        return "facebook"
    return "other"

# 新增欄位
df["domain"] = df["link"].astype(str).apply(extract_domain)
df["source_type"] = df["domain"].apply(classify_source)

# 存回 CSV
df.to_csv(links_typed_csv_path, index=False)

print(f"已寫入：{links_typed_csv_path}")
print("\n前 10 筆預覽：")
print(df.head(10)[["id", "text", "link", "domain", "source_type"]])

print("\n各 domain 出現次數（前 20 名）：")
print(df["domain"].value_counts().head(20))

print("\n各 source_type 出現次數：")
print(df["source_type"].value_counts())



#@title 下載少量 gdocs / gdrive_file 樣本到本機 /content/tmp_samples
import os
import re
import requests
import pandas as pd
from urllib.parse import urlparse, parse_qs

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_typed_csv_path = os.path.join(PROJECT_ROOT, "output", "links_with_type.csv")

SAMPLE_COUNT = 3  #@param {type:"slider", "min":1, "max":3, "step":1}

df = pd.read_csv(links_typed_csv_path)

# 只選 gdocs / gdrive_file
candidates = df[df["source_type"].isin(["gdocs", "gdrive_file"])].head(SAMPLE_COUNT)

os.makedirs("/content/tmp_samples", exist_ok=True)

def extract_gdoc_id(url: str) -> str:
    # e.g. https://docs.google.com/document/d/<ID>/edit...
    m = re.search(r"/document/d/([^/]+)/", url)
    return m.group(1) if m else ""

def extract_drive_file_id(url: str) -> str:
    # 常見格式：https://drive.google.com/file/d/<ID>/view
    m = re.search(r"/file/d/([^/]+)/", url)
    if m:
        return m.group(1)
    # 其他格式試著從 query string 抓 id 參數
    q = parse_qs(urlparse(url).query)
    if "id" in q:
        return q["id"][0]
    return ""

def simple_download(url: str, dest_path: str):
    resp = requests.get(url, stream=True)
    resp.raise_for_status()
    with open(dest_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)

downloaded = []

for _, row in candidates.iterrows():
    file_id = None
    url = row["link"]
    src_type = row["source_type"]
    eid = int(row["id"])

    if src_type == "gdocs":
        # 嘗試使用 docs 的匯出文字介面
        doc_id = extract_gdoc_id(url)
        if not doc_id:
            print(f"[skip] id={eid} 無法解析 Google Docs ID")
            continue
        export_url = f"https://docs.google.com/document/d/{doc_id}/export?format=txt"
        filename = f"sample_{eid:04d}_gdoc.txt"
        dest = os.path.join("/content/tmp_samples", filename)
        try:
            simple_download(export_url, dest)
            downloaded.append(dest)
            print(f"[ok] id={eid} -> {filename}")
        except Exception as e:
            print(f"[fail] id={eid} 下載 gdoc 失敗：{e}")
    elif src_type == "gdrive_file":
        # 對一般 Drive 檔案，先直接用原始網址嘗試下載
        filename = f"sample_{eid:04d}_gdrive"
        dest = os.path.join("/content/tmp_samples", filename)
        try:
            simple_download(url, dest)
            downloaded.append(dest)
            print(f"[ok] id={eid} -> {filename}")
        except Exception as e:
            print(f"[fail] id={eid} 下載 gdrive 檔失敗：{e}")

print("=== 已下載的樣本檔案 ===")
for path in downloaded:
    try:
        size_kb = os.path.getsize(path) / 1024
        print(f"{os.path.basename(path)}\t{size_kb:6.1f} KB")
    except OSError:
        print(os.path.basename(path))



#@title 隨機抽樣下載 Google Docs / Drive 檔 1–3 份到 /content/tmp_samples
import os
import re
import requests
import pandas as pd
from urllib.parse import urlparse, parse_qs  # 解析 URL [web:206]

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_typed_csv_path = os.path.join(PROJECT_ROOT, "output", "links_with_type.csv")

SAMPLE_COUNT = 3  #@param {type:"slider", "min":1, "max":3, "step":1}

df = pd.read_csv(links_typed_csv_path)

# 只選 gdocs / gdrive_file，然後隨機抽樣
candidates = df[df["source_type"].isin(["gdocs", "gdrive_file"])]
sampled = candidates.sample(n=min(SAMPLE_COUNT, len(candidates)), random_state=None)

os.makedirs("/content/tmp_samples", exist_ok=True)

def extract_gdoc_id(url: str) -> str:
    # e.g. https://docs.google.com/document/d/<ID>/edit...
    m = re.search(r"/document/d/([^/]+)/", url)
    return m.group(1) if m else ""

def extract_drive_file_id(url: str) -> str:
    # 常見格式：https://drive.google.com/file/d/<ID>/view
    m = re.search(r"/file/d/([^/]+)/", url)
    if m:
        return m.group(1)
    # 其他格式：嘗試從 query string 抓 id 參數
    q = parse_qs(urlparse(url).query)
    if "id" in q:
        return q["id"][0]
    return ""

def simple_download(url: str, dest_path: str):
    # 簡單 HTTP 下載，適合先測試樣本 [web:243][web:248]
    resp = requests.get(url, stream=True)
    resp.raise_for_status()
    with open(dest_path, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)

downloaded = []

print("本次抽樣的 id 與來源：")
print(sampled[["id", "text", "link", "source_type"]])

for _, row in sampled.iterrows():
    file_id = None
    url = row["link"]
    src_type = row["source_type"]
    eid = int(row["id"])

    if src_type == "gdocs":
        doc_id = extract_gdoc_id(url)
        if not doc_id:
            print(f"[skip] id={eid} 無法解析 Google Docs ID")
            continue
        export_url = f"https://docs.google.com/document/d/{doc_id}/export?format=txt"
        filename = f"sample_{eid:04d}_gdoc.txt"
        dest = os.path.join("/content/tmp_samples", filename)
        try:
            simple_download(export_url, dest)
            downloaded.append(dest)
            print(f"[ok] id={eid} -> {filename}")
        except Exception as e:
            print(f"[fail] id={eid} 下載 gdoc 失敗：{e}")
    elif src_type == "gdrive_file":
        # 先用原始網址嘗試下載，之後再視實際 MIME type 決定怎麼處理
        filename = f"sample_{eid:04d}_gdrive"
        dest = os.path.join("/content/tmp_samples", filename)
        try:
            simple_download(url, dest)
            downloaded.append(dest)
            print(f"[ok] id={eid} -> {filename}")
        except Exception as e:
            print(f"[fail] id={eid} 下載 gdrive 檔失敗：{e}")

print("=== 已下載的樣本檔案 ===")
for path in downloaded:
    try:
        size_kb = os.path.getsize(path) / 1024
        print(f"{os.path.basename(path)}\t{size_kb:6.1f} KB")
    except OSError:
        print(os.path.basename(path))



"""#@title 儲存所有連結網域類型及其次數到 CSV 檔案"""

import os

# Assuming PROJECT_ROOT and OUTPUT_DIR are already defined from previous cells
# If not, you might need to re-run the initialization cell or define them here.
# For example:
# PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
# OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")

domain_frequencies_csv_path = os.path.join(OUTPUT_DIR, "domain_frequencies.csv")

# domain_counts was calculated in a previous step
domain_counts.to_csv(domain_frequencies_csv_path, header=['frequency'])

print(f"所有網域類型及其次數已儲存至：{domain_frequencies_csv_path}")

"""## Count Domain Frequencies

### Subtask:
Calculate the frequency of each unique domain extracted in the previous step. This will show how many times each type of link (e.g., Google Drive, Microsoft) appears.

**Reasoning**:
To calculate the frequency of each unique domain, I will use the `value_counts()` method on the 'domain' column of the `df` DataFrame. Then, I will print the total number of unique domains and the top 10 most frequent domains with their counts, as instructed.
"""

domain_counts = df['domain'].value_counts(dropna=False)

print(f"Total number of unique domains: {len(domain_counts)}")

print("\nTop 10 most frequent domains:")
for domain, count in domain_counts.head(10).items():
    print(f"{domain:30s} -> {count:4d}")

"""## Visualize Domain Distribution

### Subtask:
Generate a bar chart to visually represent the distribution of different link types (domains). This visualization will include appropriate labels and a legend.

**Reasoning**:
To visualize the distribution of domains, I will first import `matplotlib.pyplot`, then select the top 10 domains, and finally generate a bar chart with appropriate labels and title, as instructed.
"""

import matplotlib.pyplot as plt

# Select the top 10 most frequent domains
top_10_domains = domain_counts.head(10)

# Create a bar chart
plt.figure(figsize=(12, 6))
plt.bar(top_10_domains.index, top_10_domains.values, color='skyblue')

# Add title and labels
plt.title('Top 10 Most Frequent Link Domains', fontsize=16)
plt.xlabel('Domain', fontsize=12)
plt.ylabel('Frequency', fontsize=12)

# Rotate x-axis labels for better readability
plt.xticks(rotation=45, ha='right', fontsize=10)

# Ensure all elements fit within the figure
plt.tight_layout()

# Display the plot
plt.show()

"""## Final Task

### Subtask:
Summarize the findings regarding the types of links present in the dataset.

## Summary:

### Q&A
This analysis aimed to identify and quantify the types of links present in the dataset.

### Data Analysis Key Findings
*   A total of 54 unique domains were identified from the links in the dataset.
*   The most frequent domain is `docs.google.com`, appearing 1843 times, indicating a significant presence of Google Docs links.
*   `drive.google.com` is the second most frequent domain with 480 occurrences, further highlighting the prevalence of Google Drive-related content.
*   Other notable frequent domains include `reurl.cc` (304 occurrences), `1drv.ms` (Microsoft OneDrive, 272 occurrences), and `www.notion.so` (205 occurrences).
*   The top 10 most frequent domains collectively represent a substantial portion of all links in the dataset, with a clear dominance by Google's services.

### Insights or Next Steps
*   **Insight:** The dataset is heavily reliant on Google's productivity and collaboration suite (Docs and Drive) for shared links, suggesting that a significant portion of the linked content may be documents or files stored on these platforms. Microsoft OneDrive also features prominently, indicating a multi-platform environment.
*   **Next Steps:** Further investigation could involve categorizing these domains to understand the nature of the linked content (e.g., cloud storage, social media, news, personal blogs) and analyzing the content of the linked documents from the dominant domains if access is available.
"""

