# -*- coding: utf-8 -*-
"""狼友小作文整理

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdV6p5GSJOomj-M0nczAaMaOlg1JK9gR
"""

#@title 專案初始化：掛載 Drive 並建立資料夾

import os
from google.colab import drive

# 1. 掛載 Google Drive
drive.mount("/content/drive", force_remount=True)

# 2. 設定專案根目錄名稱（你可以改成自己想要的字串）
PROJECT_ROOT_NAME = "wolf_small_report"  #@param {type:"string"}

# 3. 在 MyDrive 底下建立專案資料夾樹
MYDRIVE = "/content/drive/MyDrive"
PROJECT_ROOT = os.path.join(MYDRIVE, PROJECT_ROOT_NAME)

DIRS = {
    "root": PROJECT_ROOT,
    "raw": os.path.join(PROJECT_ROOT, "raw"),
    "docs": os.path.join(PROJECT_ROOT, "docs"),
    "output": os.path.join(PROJECT_ROOT, "output"),
    "output_md": os.path.join(PROJECT_ROOT, "output", "md"),
    "output_db": os.path.join(PROJECT_ROOT, "output", "db"),
    "output_reports": os.path.join(PROJECT_ROOT, "output", "reports"),
}

for name, path in DIRS.items():
    os.makedirs(path, exist_ok=True)

print("=== 專案資料夾初始化完成 ===")
for name, path in DIRS.items():
    print(f"{name:12s} -> {path}")

#@title 解析 LINE TXT，產生連結清單 links.csv

import os
import re
import csv
from datetime import datetime

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
RAW_DIR = os.path.join(PROJECT_ROOT, "raw")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")
RAW_FILENAME = "-LINE- 小作文天地的聊天記錄20251205_1652.txt"  #@param {type:"string"}

raw_path = os.path.join(RAW_DIR, RAW_FILENAME)
links_csv_path = os.path.join(OUTPUT_DIR, "links.csv")

url_pattern = re.compile(r"https?://\S+") # Corrected: Removed extra backslash

records = []
current_date = None
pending_line = None  # 暫存「文字在上一行、網址在下一行」的情況

with open(raw_path, "r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n") # Corrected: Stripping standard newline character

        # 1. 判斷是否為日期行，例如：2025/5/2（週五）
        if re.match(r"^\d{4}/\d{1,2}/\d{1,2}", line): # Corrected: Date regex pattern
            current_date = line.strip()
            pending_line = None
            continue

        if not line.strip():
            continue

        parts = line.split("\t")
        if len(parts) < 3:
            # 可能是只有網址的一行，或其他系統訊息
            # 嘗試從這一行抓網址，若有且有 pending_line，就跟上一行合併
            urls = url_pattern.findall(line)
            if urls and pending_line is not None:
                url = urls[0]
                # Extract author_id from pending_line's author, excluding emojis
                filtered_author_from_pending = re.sub(r'[^一-龥0-9a-zA-Z]', '', pending_line.get("author") or "")
                author_id_from_pending = filtered_author_from_pending[:3]
                rec = {
                    "id": len(records) + 1,
                    "date": pending_line.get("date"),
                    "time": pending_line.get("time"),
                    "author_id": author_id_from_pending,
                    "author": pending_line.get("author"),
                    "text": pending_line.get("text"),
                    "link": url,
                }
                records.append(rec)
                pending_line = None
            continue

        time_str, author_raw, content = parts[0].strip(), parts[1].strip(), parts[2].strip()
        datetime_str = f"{current_date} {time_str}" if current_date else ""
        urls = url_pattern.findall(content)

        # Extract the first three digits for author_id, excluding emojis
        filtered_author_raw = re.sub(r'[^一-龥0-9a-zA-Z]', '', author_raw)
        author_id = filtered_author_raw[:3]

        if urls:
            # 同一行就有網址
            url = urls[0]
            text_without_url = url_pattern.sub("", content).strip()
            rec = {
                "id": len(records) + 1,
                "date": datetime_str,
                "time": time_str,
                "author_id": author_id,
                "author": author_raw,
                "text": text_without_url,
                "link": url,
            }
            records.append(rec)
            pending_line = None
        else:
            # 沒有網址，先暫存，有可能下一行才是純網址
            pending_line = {
                "date": datetime_str,
                "time": time_str,
                "author": author_raw,
                "text": content,
            }

# 將結果寫入 CSV，id 就是你要的 name（編號）
fieldnames = ["id", "date", "time", "author_id", "author", "text", "link"]
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(links_csv_path, "w", encoding="utf-8", newline="") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for rec in records:
        writer.writerow(rec)

print(f"共解析出 {len(records)} 筆連結，已寫入：{links_csv_path}")

print("\n前 10 筆預覽：")
for rec in records[:10]:
    print(
        f"{rec['id']:3d} | {rec['date']} | {rec['author_id']} | {rec['author']} | "
        f"text={rec['text'][:30]} | link={rec['link']}"
    )

#@title 統計 author / id 出現次數

import os
import pandas as pd

PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
links_csv_path = os.path.join(PROJECT_ROOT, "output", "links.csv")

df = pd.read_csv(links_csv_path)

# 統計 author 欄位的種類與次數
author_counts = df["author"].value_counts(dropna=False)

print(f"總共有 {author_counts.shape[0]} 種不同的 author / id\n")

print("出現次數前 20 名：")
for author, cnt in author_counts.head(20).items():
    print(f"{author:30s} -> {cnt:4d}")

# 若你還有單獨的「數字 id」欄位（例如叫 code），可以再多做一個統計：
if "code" in df.columns:
    code_counts = df["code"].value_counts(dropna=False)
    print(f"\n總共有 {code_counts.shape[0]} 種不同的 code\n")
    print("code 出現次數前 20 名：")
    for code, cnt in code_counts.head(20).items():
        print(f"{str(code):6s} -> {cnt:4d}")

#@title 儲存所有連結網域類型及其次數到 CSV 檔案

import os

# Assuming PROJECT_ROOT and OUTPUT_DIR are already defined from previous cells
# If not, you might need to re-run the initialization cell or define them here.
# For example:
# PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
# OUTPUT_DIR = os.path.join(PROJECT_ROOT, "output")

domain_frequencies_csv_path = os.path.join(OUTPUT_DIR, "domain_frequencies.csv")

# domain_counts was calculated in a previous step
domain_counts.to_csv(domain_frequencies_csv_path, header=['frequency'])

print(f"所有網域類型及其次數已儲存至：{domain_frequencies_csv_path}")

#@title 統計最多次出現的網址。
domain_counts = df['domain'].value_counts(dropna=False)

print(f"Total number of unique domains: {len(domain_counts)}")

print("\nTop 10 most frequent domains:")
for domain, count in domain_counts.head(10).items():
    print(f"{domain:30s} -> {count:4d}")

#@title 1. 專案初始化與資料庫同步 (Database Sync)
import os
import sqlite3
import csv
from google.colab import drive

# 1. 掛載 Google Drive
drive.mount("/content/drive", force_remount=True)

# 2. 設定路徑
PROJECT_ROOT = "/content/drive/MyDrive/wolf_small_report"
DIRS = {
    "db": os.path.join(PROJECT_ROOT, "output", "db"),
    "docs": os.path.join(PROJECT_ROOT, "docs"),
    "md": os.path.join(PROJECT_ROOT, "output", "md"),
}
for path in DIRS.values():
    os.makedirs(path, exist_ok=True)

DB_PATH = os.path.join(DIRS["db"], "wolf_report.db")
LINKS_CSV = os.path.join(PROJECT_ROOT, "output", "links_with_type.csv")

# 3. 初始化資料庫 Schema
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # 主表
    c.execute('''
    CREATE TABLE IF NOT EXISTS essays (
        id INTEGER PRIMARY KEY,
        link TEXT,
        source_type TEXT,
        original_title TEXT,
        local_text_path TEXT,
        image_count INTEGER DEFAULT 0,
        download_status TEXT DEFAULT 'pending',
        analysis_status TEXT DEFAULT 'pending',
        markdown_status TEXT DEFAULT 'pending',
        error_log TEXT
    )
    ''')

    # 子表
    c.execute('''
    CREATE TABLE IF NOT EXISTS essay_scores (
        essay_id INTEGER PRIMARY KEY,
        target_name TEXT,
        target_code TEXT,
        analysis_score INTEGER,
        analysis_comment TEXT,
        risk_score INTEGER,
        risk_comment TEXT,
        short_summary TEXT
    )
    ''')
    conn.commit()
    return conn

# 4. 從 CSV 匯入資料
def ingest_links():
    if not os.path.exists(LINKS_CSV):
        print(f"❌ 找不到 CSV 檔：{LINKS_CSV}")
        return

    conn = init_db()
    c = conn.cursor()

    print(f"📂 正在讀取 {LINKS_CSV}...")
    try:
        # 強制使用 \t 作為分隔符號
        with open(LINKS_CSV, 'r', encoding='utf-8') as f:
            # 直接指定 delimiter='\t'
            reader = csv.DictReader(f, delimiter='\t')

            count = 0
            new_count = 0
            for row in reader:
                count += 1
                # 簡單防呆，若讀到空行或缺少 id 則跳過
                if not row.get('id'):
                    continue

                eid = int(row['id'])
                link = row.get('link', '')
                src_type = row.get('source_type', 'unknown')
                text = row.get('text', '')

                # 檢查是否已存在
                c.execute("SELECT 1 FROM essays WHERE id = ?", (eid,))
                if c.fetchone() is None:
                    # 插入新資料
                    c.execute('''
                        INSERT INTO essays (id, link, source_type, original_title)
                        VALUES (?, ?, ?, ?)
                    ''', (eid, link, src_type, text))
                    new_count += 1

            conn.commit()
            print(f"✅ 同步完成！CSV 共有 {count} 筆，本次新增入庫: {new_count} 筆。")

    except Exception as e:
        print(f"❌ 匯入失敗: {e}")
        # 印出第一行幫助 debug
        try:
            with open(LINKS_CSV, 'r', encoding='utf-8') as f:
                print(f"檔案首行預覽: {f.readline()}")
        except:
            pass
    finally:
        conn.close()

# 執行匯入
ingest_links()

#@title 🚀 ollama自動處理，還有辨識：畫面防抖動優化 + 本地快取
import os
import time
import datetime
import sqlite3
import threading
import collections
import psutil
import requests
import json
import re
import shutil
import sys
import subprocess
import fitz
from IPython.display import clear_output, display

# --- 0. 參數控制面板 ---
#@markdown ### ⚙️ 核心設定
MODEL_NAME = "gemma3:4b" #@param ["gemma3:4b", "gemma3:1b", "qwen3:8b"]
BATCH_SIZE = 48          #@param {type:"slider", min:1, max:50, step:1}
SYNC_INTERVAL = 100       #@param {type:"integer"} 每處理幾筆同步回 Drive
RESET_ALL_PROGRESS = False #@param {type:"boolean"}
MAX_LOOPS = 1000

#@markdown ### 🖥️ 顯示設定
MAX_LOG_LINES = 5        #@param {type:"slider", min:1, max:20, step:1} 顯示最近幾筆日誌

#@markdown ### 🛠️ 路徑設定
DRIVE_DB_PATH = "/content/drive/MyDrive/wolf_small_report/output/db/wolf_report.db"
LOCAL_DB_PATH = "/content/wolf_report_local.db" # Colab 本地快取
LOG_DB_PATH = "/content/drive/MyDrive/wolf_small_report/output/db/logs.sqlite"
DIRS = {"docs": "/content/drive/MyDrive/wolf_small_report/docs/raw_text"}
for d in DIRS.values(): os.makedirs(d, exist_ok=True)

# --- 1. 資料庫同步管理 (核心新功能) ---
def init_local_db():
    """啟動時：將 Drive DB 複製到 Local"""
    print(f"🚚 正在將資料庫從 Drive 複製到本地快取...")
    if os.path.exists(DRIVE_DB_PATH):
        shutil.copy2(DRIVE_DB_PATH, LOCAL_DB_PATH)
        print("✅ 複製完成！接下來所有操作將在本地高速進行。")
    else:
        print("⚠️ Drive 上找不到資料庫，將在本地建立新檔。")

def sync_to_drive():
    """同步時：將 Local DB 覆蓋回 Drive"""
    print(f"💾 [同步] 正在將進度寫回 Google Drive...")
    try:
        shutil.copy2(LOCAL_DB_PATH, DRIVE_DB_PATH)
        print(f"✅ 同步成功！")
    except Exception as e:
        print(f"❌ 同步失敗: {e}")

# --- 2. Ollama ---
def install_ollama_if_needed():
    if shutil.which("ollama"): return
    print("🚀 安裝 Ollama...")
    subprocess.run("curl -fsSL https://ollama.com/install.sh | sh", shell=True, check=True)

def ensure_ollama_warmup():
    print(f"🔥 啟動 Ollama ({MODEL_NAME})...")
    subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(10):
        try: requests.get("http://localhost:11434", timeout=2); break
        except: time.sleep(1)

    print(f"📥 檢查模型 {MODEL_NAME}...")
    res = subprocess.run(["ollama", "list"], capture_output=True, text=True)
    if MODEL_NAME not in res.stdout:
        print(f"⬇️ 下載中...")
        subprocess.run(["ollama", "pull", MODEL_NAME], check=True)

# --- 3. 重置 ---
def reset_progress():
    if not RESET_ALL_PROGRESS: return
    print("⚠️ 正在重置進度 (操作本地 DB)...")
    conn = sqlite3.connect(LOCAL_DB_PATH)
    c = conn.cursor()
    c.execute("UPDATE essays SET download_status='pending', analysis_status='pending', local_text_path=NULL")
    c.execute("DELETE FROM essay_scores")
    conn.commit(); conn.close()
    sync_to_drive() # 重置後馬上同步一次
    print("✅ 重置並同步完成")

# --- 4. 下載 ---
try: import gdown
except ImportError: subprocess.run(["pip", "install", "gdown"], check=True); import gdown
def extract_gdoc_id(url): return re.search(r'/d/([a-zA-Z0-9-_]+)', url).group(1) if re.search(r'/d/([a-zA-Z0-9-_]+)', url) else None

def real_download(url, output_path):
    if "drive.google.com" not in url and "docs.google.com" not in url: return False, "Skip: 非 Google"
    file_id = extract_gdoc_id(url)
    if not file_id: return False, "無效 ID"
    try:
        if "docs.google.com/document" in url:
            resp = requests.get(f"https://docs.google.com/document/d/{file_id}/export?format=txt", timeout=10)
            if resp.status_code == 200:
                with open(output_path, "w", encoding="utf-8") as f: f.write(resp.text)
                return True, "GDocs OK"
            return False, f"Err: {resp.status_code}"
        elif "drive.google.com/file" in url:
            gdown.download(id=file_id, output=output_path, quiet=True, fuzzy=True)
            if os.path.exists(output_path): return True, "GDrive OK"
            return False, "GDrive Fail"
    except Exception as e: return False, str(e)
    return False, "不支援"

# --- 5. Log & Display (已優化防抖動) ---
class LogManager:
    def __init__(self, max_lines):
        self.buffer_logs = collections.deque(maxlen=max_lines)
        self.lock = threading.Lock()
    def update_log(self, eid, c_info, r_info, level="INFO"):
        with self.lock:
            found = False; new_buffer = collections.deque(maxlen=self.buffer_logs.maxlen)
            # 嘗試更新現有的 log entry
            for item in self.buffer_logs:
                if item[0] == eid:
                    item = (eid, level, c_info, r_info)
                    found = True
                new_buffer.append(item)
            if not found:
                new_buffer.append((eid, level, c_info, r_info))
            self.buffer_logs = new_buffer
    def get_logs(self):
        with self.lock:
            return list(self.buffer_logs)

class DisplayManager(threading.Thread):
    def __init__(self, stats, log_mgr):
        super().__init__(); self.stats = stats; self.log_mgr = log_mgr; self.running = True; self.daemon = True
    def run(self):
        # 初始清除一次
        clear_output(wait=True)
        while self.running:
            self._refresh()
            time.sleep(0.5) # 降低刷新頻率至 0.5s，減少閃爍

    def _refresh(self):
        logs = self.log_mgr.get_logs()
        status = self.stats.get("status", "待機"); task = self.stats.get("task", "")
        processed = self.stats.get("processed", 0); total = self.stats.get("total", 0)
        unsynced = self.stats.get("unsynced", 0)

        # 構建輸出字串，一次性 print 避免多次 I/O
        output_str = []
        output_str.append(f"📊 Wolf Report v98.1 (Local Mode - Sync every {SYNC_INTERVAL})")
        output_str.append("=" * 80)

        # 只顯示固定行數的 logs
        for eid, level, l1, l2 in logs:
            color = "\033[92m" if level=="SUCCESS" else "\033[91m" if level=="ERROR" else "\033[93m" if level=="BUSY" else "\033[97m"
            # 截斷過長的字串以防換行導致抖動
            l1_short = l1[:75] + "..." if len(l1) > 75 else l1
            l2_short = l2[:75] + "..." if len(l2) > 75 else l2
            output_str.append(f"\033[90m  {l1_short}\033[0m")
            output_str.append(f"{color}  └── {l2_short}\033[0m")
            output_str.append("-" * 40)

        # 補齊空白行以維持畫面高度固定
        current_lines = len(logs) * 3
        target_lines = MAX_LOG_LINES * 3
        if current_lines < target_lines:
            output_str.append("\n" * (target_lines - current_lines))

        cpu = psutil.cpu_percent(); ram = psutil.virtual_memory().percent
        progress = processed / total if total > 0 else 0
        bar_len = 20
        filled_len = int(bar_len * progress)
        bar = "█" * filled_len + "░" * (bar_len - filled_len)

        status_line = f"CPU:{cpu}% | RAM:{ram}% | [{status}] {bar} ({processed}/{total}) | ⚠️ 未同步: {unsynced}"
        output_str.append(status_line)

        # 使用 clear_output(wait=True) 配合一次性 print
        clear_output(wait=True)
        print("\n".join(output_str), end="")

    def stop(self): self.running = False

# --- 6. Logic ---
def extract_text(path):
    if not os.path.exists(path): return ""
    text = ""
    try:
        with open(path, 'rb') as f: header = f.read(4)
        if header == b'%PDF':
            doc = fitz.open(path)
            for page in doc: text += page.get_text() + "\n"
        else:
            with open(path, 'r', encoding='utf-8', errors='ignore') as f: text = f.read()
    except: return ""
    return text.strip()

def call_ollama_verbose(prompt):
    try:
        res = requests.post("http://localhost:11434/api/generate",
              json={"model": MODEL_NAME, "prompt": prompt, "stream": False,
                    "options": {"temperature": 0.1, "num_ctx": 8192}}, timeout=60)
        return res.json().get("response", "").strip()
    except Exception as e: return f"ERR:{str(e)[:10]}"

def analyze_item(eid, text, author_info, log_mgr):
    c_info = f"[ID: {eid:04d}] {author_info}"

    log_mgr.update_log(eid, c_info, "⏳ 1/3 標的...", "BUSY")
    t = call_ollama_verbose(f"文章：\n{text[:1500]}\n分析哪支股票？只回【名稱 代碼】。")
    target = t.split("\n")[0].replace("。", "").replace("標的：", "").strip()

    log_mgr.update_log(eid, c_info, f"🎯 {target} | ⏳ 2/3 評分...", "BUSY")
    s = call_ollama_verbose(f"文章：\n{text[:2000]}\n給分析評分(1-15)。只回數字。")
    match = re.search(r'\d+', s)
    score = match.group() if match else "N/A"

    log_mgr.update_log(eid, c_info, f"🎯 {target} | ⭐ {score} | ⏳ 3/3 摘要...", "BUSY")
    summ = call_ollama_verbose(f"文章：\n{text[:2000]}\n繁中一句話摘要(30字內)。")
    summary = summ.replace("\n", " ").strip()

    final_res = f"🎯 {target} | ⭐ {score}/15 | 📝 {summary}"
    log_mgr.update_log(eid, c_info, final_res, "SUCCESS")
    return target, score, summary

def main():
    install_ollama_if_needed()
    ensure_ollama_warmup()

    init_local_db()
    reset_progress()

    # 傳入 MAX_LOG_LINES 設定
    log_mgr = LogManager(MAX_LOG_LINES)
    stats = {"status": "初始化", "processed": 0, "total": 0, "unsynced": 0}
    display = DisplayManager(stats, log_mgr); display.start()

    conn = None
    unsynced_count = 0

    try:
        conn = sqlite3.connect(LOCAL_DB_PATH)
        c = conn.cursor()
        c.execute("SELECT COUNT(*) FROM essays WHERE analysis_status != 'done' AND download_status != 'failed'")
        stats["total"] = c.fetchone()[0]

        loop = 0
        while loop < MAX_LOOPS:
            loop += 1
            c.execute("SELECT id, link, source_type, local_text_path, download_status, original_title FROM essays WHERE analysis_status != 'done' AND download_status != 'failed' LIMIT ?", (BATCH_SIZE,))
            rows = c.fetchall()
            if not rows: stats["status"] = "無可用任務"; break

            for row in rows:
                eid, link, src_type, local_path, dl_status, title = row
                stats["status"] = "工作中"; stats["task"] = f"ID {eid}"

                # Download
                if dl_status != 'success' or not local_path or not os.path.exists(local_path):
                    temp_path = os.path.join(DIRS["docs"], f"essay_{eid:04d}.txt")
                    ok, msg = real_download(link, temp_path)
                    if ok:
                        local_path = temp_path
                        c.execute("UPDATE essays SET download_status='success', local_text_path=? WHERE id=?", (temp_path, eid))
                        conn.commit()
                    else:
                        log_mgr.update_log(eid, f"[ID: {eid:04d}] {title[:20]}...", f"❌ 跳過: {msg}", "ERROR")
                        c.execute("UPDATE essays SET download_status='failed' WHERE id=?", (eid,))
                        conn.commit(); continue

                # Analyze
                text = extract_text(local_path)
                if text and len(text) > 10:
                    auth_display = f"Title: {title[:30]}..."
                    t_name, t_score, t_summ = analyze_item(eid, text, auth_display, log_mgr)
                    c.execute("INSERT OR REPLACE INTO essay_scores (essay_id, target_name, analysis_score, short_summary) VALUES (?, ?, ?, ?)", (eid, t_name, t_score, t_summ))
                    c.execute("UPDATE essays SET analysis_status='done' WHERE id=?", (eid,))
                    conn.commit()

                    stats["processed"] += 1
                    unsynced_count += 1
                    stats["unsynced"] = unsynced_count
                else:
                    c.execute("UPDATE essays SET analysis_status='skipped' WHERE id=?", (eid,))
                    conn.commit()

                if unsynced_count >= SYNC_INTERVAL:
                    stats["status"] = "同步中..."
                    conn.close()
                    sync_to_drive()
                    conn = sqlite3.connect(LOCAL_DB_PATH)
                    c = conn.cursor()
                    unsynced_count = 0
                    stats["unsynced"] = 0

    except Exception as e: print(f"\n❌ 執行錯誤: {e}")
    finally:
        if conn: conn.close()
        print("\n🔄 最終同步...")
        sync_to_drive()
        display.stop(); display.join(); print("\n✅ 執行結束")

if __name__ == "__main__": main()

#@title 🩺 診斷模式：檢查輸入與輸出 (Debug)
import sqlite3
import os
import requests
import json

DB_PATH = "/content/drive/MyDrive/wolf_small_report/output/db/wolf_report.db"
MODEL_NAME = "qwen3:8b"

def debug_ollama_input():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # 1. 隨機抓一筆「已下載成功」的任務
    c.execute("SELECT id, local_text_path, original_title FROM essays WHERE download_status='success' LIMIT 1")
    row = c.fetchone()
    conn.close()

    if not row:
        print("❌ 找不到已下載成功的任務，無法診斷。請先讓 Pipeline 跑幾筆下載。")
        return

    eid, path, title = row
    print(f"🔬 正在診斷 ID: {eid} | Title: {title}")
    print(f"📂 檔案路徑: {path}")

    # 2. 檢查檔案內容
    if not os.path.exists(path):
        print("❌ 檔案不存在！路徑錯誤。")
        return

    try:
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except Exception as e:
        print(f"❌ 讀檔失敗: {e}")
        return

    print("-" * 40)
    print(f"📄 檔案內容預覽 (前 200 字):\n{content[:200]}")
    print("-" * 40)

    if not content.strip():
        print("⚠️ 警告：檔案內容是空的！這就是為什麼 Ollama 沒反應！")
        return

    # 3. 測試 Ollama 呼叫
    print("🤖 正在發送測試請求給 Ollama...")
    prompt = f"這是一篇測試文章：\n{content[:500]}\n\n請問這篇文章的第一句話是什麼？"

    url = "http://localhost:11434/api/generate"
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {"num_ctx": 4096}
    }

    try:
        resp = requests.post(url, json=payload)
        if resp.status_code == 200:
            res_json = resp.json()
            print(f"✅ Ollama 回應成功！\n原始回應: {res_json.get('response')}")
        else:
            print(f"❌ Ollama 回應錯誤: {resp.status_code} - {resp.text}")
    except Exception as e:
        print(f"❌ 連線失敗: {e}")

debug_ollama_input()

#@title 4. 報告生成器：產出 Markdown (Export to MD)
import sqlite3
import os

# --- 設定路徑 ---
DB_PATH = "/content/drive/MyDrive/wolf_small_report/output/db/wolf_report.db"
MD_DIR = "/content/drive/MyDrive/wolf_small_report/output/md"
os.makedirs(MD_DIR, exist_ok=True)

def generate_markdown_reports():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # 1. 撈取「已分析完成」但「還沒產出 MD」的文章
    # 我們會 join essay_scores 表來拿到 AI 的分析結果
    query = """
        SELECT
            e.id, e.link, e.original_title,
            s.target_name, s.target_code,
            s.analysis_score, s.analysis_comment,
            s.risk_score, s.risk_comment,
            s.short_summary
        FROM essays e
        JOIN essay_scores s ON e.id = s.essay_id
        WHERE e.analysis_status = 'done'
          AND e.markdown_status = 'pending'
    """
    c.execute(query)
    rows = c.fetchall()

    if not rows:
        print("🎉 所有已分析的文章都已生成報告！")
        conn.close()
        return

    print(f"📄 準備生成 {len(rows)} 份 Markdown 報告...")

    for row in rows:
        (eid, link, title, target, code, a_score, a_comment, r_score, r_comment, summary) = row

        # 處理一下可能為 None 的欄位
        target = target if target else "未分類"
        code = code if code else "N/A"
        summary = summary if summary else "無摘要"

        # --- 2. 檔名設計 ---
        # 格式：0006_台積電_2330.md
        safe_target = target.replace("/", "_").replace("\\", "_")
        filename = f"{eid:04d}_{safe_target}_{code}.md"
        filepath = os.path.join(MD_DIR, filename)

        # --- 3. Markdown 內容樣板 ---
        md_content = f"""# {target} ({code}) - 投資分析報告

> **編號**: {eid}
> **原始連結**: [{title}]({link})
> **AI 摘要**: {summary}

---

## 📊 評分總覽
| 面向 | 分數 (1-5) | 評語 |
| :--- | :---: | :--- |
| **分析邏輯** | {a_score} ⭐ | {a_comment} |
| **風險係數** | {r_score} ⚠️ | {r_comment} |

## 📝 詳細分析
(此處為 AI 根據原文的深度解析...)

* **標的**: {target}
* **代碼**: {code}
* **風險提示**: {r_comment}

---
*Generated by Wolf Small Report System*
"""

        # --- 4. 寫檔與更新狀態 ---
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(md_content)

            # 更新 DB 狀態
            c.execute("UPDATE essays SET markdown_status='done' WHERE id=?", (eid,))
            # 順便記錄 md 檔路徑 (雖然我們剛剛說極簡，但留個紀錄也好)
            # c.execute("UPDATE essay_outputs SET markdown_path=? ...") # 這裡簡化省略

            print(f"✅ 生成: {filename}")

        except Exception as e:
            print(f"❌ 生成失敗 ID {eid}: {e}")

    conn.commit()
    conn.close()
    print("🏁 報告生成完畢！")

if __name__ == "__main__":
    generate_markdown_reports()